GTNewHorizons/ThaumicEnergistics

build.gradle, src/main/java/thaumicenergistics/client/gui/GuiEssentiaIO.java, src/main/java/thaumicenergistics/client/gui/buttons/GuiButtonCraftingMode.java, src/main/java/thaumicenergistics/client/textures/AEStateIconsEnum.java, src/main/java/thaumicenergistics/common/container/ContainerDistillationPatternEncoder.java, src/main/java/thaumicenergistics/common/container/ContainerEssentiaCell.java, src/main/java/thaumicenergistics/common/container/ContainerEssentiaCellTerminalBase.java, src/main/java/thaumicenergistics/common/container/ContainerEssentiaCellWorkbench.java, src/main/java/thaumicenergistics/common/container/ContainerEssentiaTerminal.java, src/main/java/thaumicenergistics/common/container/ContainerEssentiaVibrationChamber.java, src/main/java/thaumicenergistics/common/container/ContainerKnowledgeInscriber.java, src/main/java/thaumicenergistics/common/container/ContainerPartArcaneCraftingTerminal.java, src/main/java/thaumicenergistics/common/container/ContainerPartEssentiaIOBus.java, src/main/java/thaumicenergistics/common/container/ContainerPartEssentiaLevelEmitter.java, src/main/java/thaumicenergistics/common/container/ContainerPartEssentiaStorageBus.java, src/main/java/thaumicenergistics/common/container/ContainerWirelessEssentiaTerminal.java, src/main/java/thaumicenergistics/common/network/packet/client/Packet_C_EssentiaIOBus.java, src/main/java/thaumicenergistics/common/network/packet/server/Packet_S_EssentiaIOBus.java, src/main/java/thaumicenergistics/common/parts/AEPartsEnum.java, src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java, src/main/java/thaumicenergistics/common/parts/PartEssentiaStorageMonitor.java, src/main/java/thaumicenergistics/common/parts/ThEPartEssentiaIOBus_Base.java, src/main/java/thaumicenergistics/implementaion/ThEMultiCraftingTracker.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6098
=> Crafting card support for Essentia Export Bus

build.gradle, src/main/java/thaumicenergistics/common/container/ContainerPartArcaneCraftingTerminal.java, src/main/java/thaumicenergistics/common/integration/ModuleNEI.java, src/main/java/thaumicenergistics/common/network/NetworkHandler.java, src/main/java/thaumicenergistics/common/network/packet/server/Packet_S_NEIRecipe.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6479
=> Added proper NEI overlay

build.gradle, src/main/java/thaumicenergistics/common/parts/ThEPartBase.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7146
=> Null check against world access while unloading

build.gradle, src/main/java/thaumicenergistics/common/integration/tc/ArcaneCraftingPattern.java, src/main/java/thaumicenergistics/common/tiles/TileArcaneAssembler.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7178
=> fixed damageable ingredients usage and a bit cleanup

build.gradle, src/main/java/thaumicenergistics/common/integration/tc/EssentiaTileContainerHelper.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7290
=> Support for various essentia containers

build.gradle, src/main/java/thaumicenergistics/common/integration/tc/ArcaneRecipeHelper.java
(https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7492)
=> Add alternative recipe aspect cost check

build.gradle, src/main/java/thaumicenergistics/common/inventory/HandlerKnowledgeCore.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8208
=> Allow updating obsolete patterns

src/main/java/thaumicenergistics/common/inventory/HandlerKnowledgeCore.java
Add null checks to prevent crash
Fixes [issue](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8494)
=> Fix knowledge inscriber crash

src/main/java/thaumicenergistics/common/container/ContainerKnowledgeInscriber.java
https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/24
=> Allow shapeless recipes with duplicate ingredients

src/main/java/thaumicenergistics/common/inventory/HandlerEssentiaStorageBusContainer.java
(also some warnings cleanup)
Fixes(https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6335)
=> fix essentia cache monitoring void jars

src/main/java/thaumicenergistics/common/parts/PartEssentiaStorageMonitor.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9494
=> fix NPE at PartEssentiaStorageMonitor.TrackingInformation

build.gradle, dependencies.gradle, gradle.properties, src/main/java/thaumicenergistics/client/gui/GuiEssentiaCellWorkbench.java, src/main/java/thaumicenergistics/client/gui/GuiEssentiaIO.java, src/main/java/thaumicenergistics/client/gui/GuiEssentiaLevelEmitter.java, src/main/java/thaumicenergistics/client/gui/GuiEssentiaStorageBus.java, src/main/java/thaumicenergistics/client/gui/abstraction/ThEBaseGui.java, src/main/java/thaumicenergistics/common/integration/ModuleNEI.java, src/main/java/thaumicenergistics/common/integration/tc/EssentiaItemContainerHelper.java
closed GTNewHorizons/GT-New-Horizons-Modpack#10349
=> Allow NEI to mark Aspect

src/main/java/thaumicenergistics/common/integration/tc/EssentiaTileContainerHelper.java
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10522
https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/26
=> Fix Essentia Condenser interaction

build.gradle, src/main/java/thaumicenergistics/common/inventory/HandlerEssentiaStorageBusBase.java, src/main/java/thaumicenergistics/common/inventory/HandlerEssentiaStorageBusContainer.java
The old behavior is at its best described as "wonky"...
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11924
=> fix wonky storage bus under inverted mode

src/main/java/thaumicenergistics/common/registries/AEAspectRegister.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12770
I have no real opinion on the aspects of these blocks. If someone has a preference they can be changed
=> Add basic accelerator aspects

dependencies.gradle, src/main/java/thaumicenergistics/api/IThEConfig.java, src/main/java/thaumicenergistics/common/ConfigurationHandler.java, src/main/java/thaumicenergistics/common/integration/IntegrationCore.java, src/main/java/thaumicenergistics/common/integration/ModuleAe2fc.java, src/main/java/thaumicenergistics/common/integration/ModuleCC.java, src/main/java/thaumicenergistics/common/integration/ModuleEC2.java, src/main/java/thaumicenergistics/common/integration/ModuleNEI.java, src/main/java/thaumicenergistics/common/integration/ModuleWaila.java
This build will fail until https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/130 is merged in, and dep version is correct
- Remove version checker integration as it's not needed
- Removes reflection from integration; use static init methods w/ mod loader checks
- Adds AE2FC integration: blacklist gas if set in config
=> Refactoring

src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15207
=> Fix new essentia cell crash when shift rightclicking

dependencies.gradle, gradle.properties, settings.gradle, src/main/java/thaumicenergistics/client/gui/GuiCraftAmountBridge.java
Some stuff got changed in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/483 which caused the crash. 
Namely amountToCraft -> amountTextField but it's all for the better as it allows us to lose that stinky reflection.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15699
=> Fix crash when starting autocraft from arcane terminal

src/main/java/thaumicenergistics/client/gui/GuiArcaneCraftingTerminal.java, src/main/java/thaumicenergistics/client/gui/GuiCraftingStatusBridge.java, src/main/java/thaumicenergistics/client/gui/GuiEssentiaCellTerminal.java, src/main/java/thaumicenergistics/common/ThEGuiHandler.java, src/main/java/thaumicenergistics/common/container/ContainerEssentiaCell.java, src/main/java/thaumicenergistics/common/container/ContainerEssentiaCellTerminalBase.java, src/main/java/thaumicenergistics/common/container/ContainerEssentiaTerminal.java, src/main/java/thaumicenergistics/common/container/ContainerPartArcaneCraftingTerminal.java, src/main/java/thaumicenergistics/common/container/ContainerWirelessEssentiaTerminal.java, src/main/java/thaumicenergistics/common/network/packet/server/Packet_S_ArcaneCraftingTerminal.java, src/main/java/thaumicenergistics/common/network/packet/server/Packet_S_EssentiaCellTerminal.java
This adds the "crafting status" button to the Arcane Terminal. I've tested it in singleplayer and in multiplayer. It works, except that there is no tooltip for the button, because ThE seems to do tooltips very differently than AE2.
=> Added crafting status button to ThE terminals

src/main/java/thaumicenergistics/client/gui/GuiArcaneCraftingTerminal.java, src/main/java/thaumicenergistics/client/gui/GuiEssentiaCellTerminal.java, src/main/java/thaumicenergistics/client/gui/abstraction/GuiConstants_ACT.java, src/main/java/thaumicenergistics/client/gui/abstraction/GuiConstants_ECT.java, src/main/java/thaumicenergistics/client/gui/buttons/GuiButtonCraftingStatus.java, src/main/java/thaumicenergistics/client/gui/buttons/ThEStateButton.java, src/main/java/thaumicenergistics/client/textures/AEStateIconsEnum.java
Now it can show up tooltip correctly
and swap button sequence in ACT.
| Before | Now |
| :-: | :-: |
| ![image](https://github.com/user-attachments/assets/d01a2396-66eb-4326-b4c3-0a2d3d373d92) | ![image](https://github.com/user-attachments/assets/60a5ba81-e686-4881-8b1d-83441a78592b) |
=> Change crafting status button to ThE button

dependencies.gradle, src/main/java/thaumicenergistics/common/parts/PartEssentiaStorageBus.java
Depends on https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/526
=> Remove blinkCell override

src/main/java/thaumicenergistics/common/inventory/HandlerItemEssentiaCell.java, src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java
reduce repeat method
and change for network status gui
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/575
=> add blue cell light info for network status

src/main/java/thaumicenergistics/common/tiles/TileAdvancedInfusionProvider.java
add check before adding matrix into matrixs list, to prevent multi binding issue
=> add check before adding matrix into list

dependencies.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, repositories.gradle, src/main/java/thaumicenergistics/client/gui/GuiCraftAmountBridge.java, src/main/java/thaumicenergistics/common/inventory/HandlerWirelessEssentiaTerminal.java
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19577
This is fixed by simply compiling with the latest version of AE2.
- Implement the methods added to `IEnergyGrid`.
- Fixes math expression is not working in CraftAmountGui.
=> Adapt to AE2 changes

src/main/resources/assets/thaumicenergistics/lang/en_US.lang
change "Workig" to "Working" and "binded" to "bound"
=> correct english localization spelling

dependencies.gradle, src/main/java/thaumicenergistics/common/parts/PartEssentiaStorageMonitor.java, src/main/java/thaumicenergistics/implementaion/ThEInteractionHelper.java
=> fix and port the new Localization message system and update AE2 dependency.

src/main/java/thaumicenergistics/common/tiles/abstraction/TileProviderBase.java
before: https://spark.lucko.me/YX7GwTEFM0
after: https://spark.lucko.me/C3QpPrU6DD
This reduces the lag from world accelerated thaumatoriums by checking if a given aspect can be crafted before starting a job. This isn't a perfect profile because I suspect that job starting is an O(n) operation, so having such a small setup isn't a good benchmark. Still, there's a noticeable difference in the mspt in the profiles (2.5ms vs 1.5ms, a 1ms improvement).
fixes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20931
=> Reduce lag from world accelerated thaumatoriums
